/*jshint unused:false */

module.exports = {
  SERVER_AUTH_CHALLENGE: 0x00,
  SERVER_AUTH_REPLY: 0x01,
  SERVER_CONFIG_CHANGE_NOTIFY: 0x02,
  SERVER_USERINFO_CHANGE_NOTIFY: 0x03,
  SERVER_DOWNLOAD_INTERVAL_BEGIN: 0x04,
  SERVER_DOWNLOAD_INTERVAL_WRITE: 0x05,
  CLIENT_AUTH_USER: 0x80,
  CLIENT_SET_USERMASK: 0x81,
  CLIENT_SET_CHANNEL: 0x82,
  CLIENT_UPLOAD_INTERVAL_BEGIN: 0x83,
  CLIENT_UPLOAD_INTERVAL_WRITE: 0x84,
  CHAT_MESSAGE: 0xC0,
  KEEP_ALIVE: 0xFD,
  EXTENDED: 0xFE,
  INVALID: 0xFF,
  KEEP_ALIVE_PACKET: new Buffer('FD00000000', 'hex').toString()
};
